version: "3"
services:
  python:
    build:
      context: ./recommend_products
      dockerfile: Dockerfile
    ports:
      - ${PYTHON_PORT}:80
    hostname: python
    volumes:
      - ./recommend_products:/app

  node:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./user:/app
